// Dify 代理 API（由你自己的小后端持有密钥并转发）
// 生产：Nginx 将 /api/dify/* 转发到 sugar-guard-proxy（Node/Python）
export const API_BASE_URL = '/api/dify';

// 这里只保留“应用标识”，不包含任何真实 Dify Key
export const DIFY_APPS = {
  DOCTOR_ZHAO: 'DOCTOR_ZHAO',
  DOCTOR_LI: 'DOCTOR_LI',
  DOCTOR_ZHANG: 'DOCTOR_ZHANG',
  DATA_MGMT: 'DATA_MGMT',
  DB_WORKFLOW: 'DB_WORKFLOW',
  RISK_PREDICTION: 'RISK_PREDICTION',
  SCHEME_CUSTOMIZATION: 'SCHEME_CUSTOMIZATION',
  CHECKIN_ANALYSIS: 'CHECKIN_ANALYSIS',
  HEALTH_CONSULTATION: 'HEALTH_CONSULTATION',
  AI_MGMT_ASSISTANT: 'AI_MGMT_ASSISTANT',
  DIABETES_EXPERT: 'DIABETES_EXPERT',
  SMART_ASSISTANT: 'SMART_ASSISTANT',
} as const;
